name: mesoricin_env
channels:
  - defaults
dependencies:
  - python=3.8
  - numpy>=1.13.3
  - pandas>=1.2.4
  - scipy<=1.7.0
  - scikit-learn=0.24.2
  - seaborn
  - tqdm
  - matplotlib
  - pip
  - pip:
      - modlamp
      - antifungal
